### ISSUE TITLE
Check how Trello is integrated with Github

### ISSUE THREAD

**Issue by fominykh** [Jorest/TrelloTesting#1]
This is a description of the test issue in the TrelloTesting repository.

**Comment by fominykh** [comment]
@Jorest just checking what I will see in Trello - this is a comment, tagging another user.

**Comment by fominykh** [comment]
@Jorest how is this Github repo connected to Trello? I do not see yet...

**Comment by Jorest** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make an issue and atach](https://trello.com/c/z4vxuuvH/3-make-an-issue-and-atach)
